### ISSUE TITLE
Lisans eksik

### ISSUE THREAD

**Issue by TheYkk** [msusur/codefiction-stats-graphql#36]
projede suan lisans goremedik ekleyebilirseniz guzel olur

**Comment by msusur** [comment]
Bir kutuphane gibi alip kullanilmayacagi icin bence su anda buna gerek yok. Bu projenin acik olmasinin amaci temel olarak Graphql'in kullanim alanlarini acikca gosterebilmekti. Dolayisiyla buradaki yontemleri ogrenip herkes istedigi projede uygulayabilir ama tekrar kullanilabilecek bir kod parcasi oldugunu dusunmuyorum.
