### ISSUE TITLE
node_modules have big size

### ISSUE THREAD

**Issue by TheYkk** [msusur/codefiction-stats-graphql#37]
![image](https://user-images.githubusercontent.com/21688838/55420644-2bc4bf80-5580-11e9-9183-ebd1889d9686.png)
![image](https://user-images.githubusercontent.com/21688838/55420671-426b1680-5580-11e9-9b9c-cb658215f36a.png)
![image](https://user-images.githubusercontent.com/21688838/55420682-4b5be800-5580-11e9-8c96-4e26879937c2.png)

### total :
![image](https://user-images.githubusercontent.com/21688838/55420771-7ba38680-5580-11e9-9896-868a214dc5ba.png)

### layers:
![image](https://user-images.githubusercontent.com/21688838/55420730-662e5c80-5580-11e9-91a6-ce37012ca4b7.png)

**Comment by msusur** [comment]
I have updated the project to start using `yarn` `workspaces` that saved around a couple of hundreds megs. 2adc77df5a124682710b57d60ac4bf38d1b5fe53 That's a good win but seems to be the best we can do unless we want to cut down some features in linting which I believe is not ideal.

In my mac this was the previous size

```sh
 60M	./node_modules
211M	./packages/stats-lambda/node_modules
533M	./packages/stats-pages/node_modules
```

and now it read as the following
```sh
4.8M	./packages/stats-pages/node_modules
 46M	./packages/stats-lambda/node_modules
516M	./node_modules
```
