### ISSUE TITLE
Stats dashboard is down due to CORS error

### ISSUE THREAD

**Issue by uguratar** [msusur/codefiction-stats-graphql#43]
Here is the error in the developer console:
`(index):1 Access to fetch at 'https://codefiction-stats.herokuapp.com/graphql' from origin 'http://stats.codefiction.tech.s3-website-eu-west-1.amazonaws.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
codefiction-stats.herokuapp.com/graphql:1 Failed to load resource: net::ERR_FAILED
App.js:71 [Network error]: TypeError: Failed to fetch`

**Comment by msusur** [comment]
Error message is misleading, the real error is happening on the server side, which is because of the fact that our free dyno's have been expired and waiting for the next month to refresh the quota 🕺 

```
2019-05-29T21:45:01.304359+00:00 heroku[router]: at=info code=H82 desc="Free app running time quota exhausted" method=OPTIONS path="/graphql" host=codefiction-stats.herokuapp.com request_id=cb91e0eb-b046-4299-8631-a1024dbee6ff fwd="46.196.69.67" dyno= connect= service= status=503 bytes= protocol=https
```
